// <auto-generated />
using System;
using GymMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009145919_addUpdateWeightTable")]
    partial class addUpdateWeightTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymMvc.Models.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Age")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone Number");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("years_of_experience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("GymMvc.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InformationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InformationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("GymMvc.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Approve")
                        .HasColumnType("bit");

                    b.Property<int?>("Receive")
                        .HasColumnType("int");

                    b.Property<int?>("Sent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GymMvc.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoacheId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("GymMvc.Models.ScheduleWorkOut", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOutId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId", "WorkOutId");

                    b.HasIndex("WorkOutId");

                    b.ToTable("ScheduleWorkOuts");
                });

            modelBuilder.Entity("GymMvc.Models.UpdateWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("NewWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UpdateWeights");
                });

            modelBuilder.Entity("GymMvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "coache"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tranier"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("GymMvc.Models.WorkOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reps")
                        .HasColumnType("int");

                    b.Property<int>("sets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkOuts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The dumbbell bench press is a version of the bench press that uses dumbbells instead of a barbell. Using two dumbbells and a bench, this exercise challenges the performer to lower both dumbbells to their chest before extending the arms to press them back up again. This bench press variation has an increased range of motion as the dumbbells can surpass the chest slightly.\r\n\r\nPrimarily targeting the chest muscles, the dumbbell press will activate the pectorals, triceps, and deltoids. The dumbbell bench press requires greater balance and stability so greater core engagement is needed.\r\n\r\nThe dumbbell bench press is great for beginners who want to build strength and stability before progressing to the barbell bench press, but equally valuable for intermediate and advanced lifters as a way to build unilateral strength and improve stability.\r\n\r\nThe dumbbell press can also be varied to regress the movement or add different challenges. For example, the neutral grip dumbbell press (palms facing each other) reduces involvement from the deltoids and places less stress on the shoulder joint, making it a suitable option for anyone wanting to focus on the chest and triceps while reducing injury risk, and the dumbbell floor press has a reduced range of movement which makes it suitable for beginners.\r\n\r\nThe dumbbell floor press has a reduced range of motion, making it a good option for beginners or those recovering from injury, while the alternating dumbbell bench press works shoulder and core stability more.",
                            Image = "dumbbell-bench-press.jpg",
                            Name = "dumbbell bench press",
                            reps = 15,
                            sets = 4
                        },
                        new
                        {
                            Id = 2,
                            Description = "The seated chest press is a fixed weight machine that replicates the movement of a bench press in a seated position. Using the seated chest press works the pectorals, deltoids, and triceps, and has less requirement for stabilisation compared to a bench press due to the support from the machine.\r\n\r\nThe seated chest press is a great place to start if you’re new to weight training. Fixed resistance machines use a pre-determined movement path which enables the correct position to be adopted throughout the exercise to ensure the intended muscle groups are being used. This allows the lifter to build strength and become familiar with the movement while minimising injury risks.",
                            Image = "seated-chest-press.jpg",
                            Name = "seated chest press",
                            reps = 10,
                            sets = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "The seated shoulder press machine is a fixed weight machine that replicates the movement of a seated shoulder press. The shoulder press machine primarily targets the deltoids, with some involvement from the triceps and clavicular head of the pecs.\r\n\r\nThe shoulder press machine is a great place to start if you’re new to weight training as it allows you to become familiar with the movement and strengthen the shoulders while minimising the risk of injury",
                            Image = "how-to-shoulder-press-mchine.jpg",
                            Name = "seated shoulder press machine",
                            reps = 12,
                            sets = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "The tricep pushdown uses a cable machine to train the tricep heads, with the medial and lateral heads mainly being targeted. The exercise involves pushing weight from around chest height down to the upper thigh. Both a straight bar and rope attachment can be used for this exercise.\r\n\r\nWith free weights, the tension is often reduced during the eccentric part of the movement (when the weight goes with gravity). Because the centre of gravity is different with a cable machine, tension is placed on the triceps throughout the entire movement, with greater focus on the eccentric portion of the movement compared to free weights, which can be beneficial for strength and hypertrophy.",
                            Image = "tricep-pushdown.png",
                            Name = "tricep pushdown",
                            reps = 12,
                            sets = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "The lat pull down machine is used to target the latissimus dorsi muscle (i.e. your back). It is typically performed seated, facing towards the machine, where you pull a long bar attached to the cable, towards your chest, and then slowly extend your arms back to starting position.\r\n\r\nThe lat pulldown can help to improve back strength and increase the size of your back muscles. It's a popular exercise for the back for beginners up until advanced gym goers. \r\n\r\nFor lat pulldown variations, check out our guides which include a step by step breakdown on how to perform the exercises below.",
                            Image = "latpulldownimage.jpg",
                            Name = "lat pulldown",
                            reps = 10,
                            sets = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "The barbell bent over row is an excellent upper body exercise that works the latissimus dorsi, the trapezius, the rhomboids, and the rear deltoids, with the core, biceps, and spinal erectors assisting the lift. The hip hinge setup of the row means that the lower body is also recruited for stability, with the glutes and hamstrings having to remain strong to maintain the correct position.\r\n\r\nThis compound exercise that builds strength and aids muscular hypertrophy, can help to improve posture, and protect the body against injury, and is well worth including in any training programme.\r\n\r\nThe barbell bent over row can use either an overhand (pronated) grip or an underhand (supinated) grip to alter which muscles are challenged. The pronated grip places greater focus on the lats, while the supinated grip recruits the biceps more. Most people can lift more load with a supinated grip.",
                            Image = "barbell-row.png",
                            Name = "barbell bent over row",
                            reps = 10,
                            sets = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "The incline dumbbell row, or chest supported row, is a variation of the dumbbell bent over row where the perform leans the chest on an incline bench for support. Using the bench for support allows the torso to be at a 45-degree angle without relying on a hip hinge, which reduces the demand on the hamstrings and glutes and allows the back muscles to be challenged without being limited by lower body fatigue.\r\n\r\nThe incline dumbbell row targets the latissimus dorsi, rhomboids, trapezius, and rear deltoids. A neutral grip (palms facing each other) is commonly used, which may feel more comfortable on the shoulder joint. However, you can choose to vary the grip to create more focus on different muscles. A supinated (underhand) grip places more challenge on the biceps, while a pronated (overhand) grip engages the lats further.\r\n\r\nThe incline dumbbell row is a good option for those new to the bent over row as the bench provides stability and the correct position to perform the movement while reducing the stress placed on the lower back. It can also help to improve muscular imbalances between the two sides as each side works independently.",
                            Image = "chest-supported-row.jpg",
                            Name = "incline dumbbell row, or chest supported row",
                            reps = 10,
                            sets = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Face pulls use a cable machine with a rope attachment to train the rear deltoids, the muscles in the back of the shoulders, with support from the traps, rhomboids and rotator cuff. Strengthening these muscles can help with poor posture, improve shoulder stability, and help with overall shoulder and back strength.\r\n\r\nThe most popular of shoulder movements typically include pressing and raise movements which mostly work the anterior and lateral delts and neglect the rear delts. Including rear delt exercises like the face pull is important for building strong, healthy shoulders. It also helps to prevent muscular imbalances between the front and back of your body, which can lead to poor posture like slumping.",
                            Image = "seated-rear-delt-fly.png",
                            Name = "Face pulls",
                            reps = 15,
                            sets = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "If you're reading this on a tablet or mobile your biceps are one of the muscles helping you hold your device. Located at the front of your upper arms, the bi-articular muscle helps control the motion of both the shoulder and elbow.  \r\n\r\nMaking up about one-third of your arms, the bicep is a highly visible muscle which means regularly performing bicep curls is a fantastically effective way to add definition and a toned look to your arms.\r\n\r\nThe biceps are one of your most-used muscles, essential to the forearm lifting motion. On a daily basis, hundreds of tasks involve bending your arm at the elbow and bicep curls will help make these actions easier to perform. An added bonus is a stronger grip, as holding the dumbbells used to perform the curls also trains your wrist and finger flexors. \r\n\r\nThe following isolation exercises will target your biceps and put you on the road to having stronger, healthier, more defined upper arms.",
                            Image = "bicep.jpg",
                            Name = "bicep curl",
                            reps = 14,
                            sets = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Squats are a great exercise if you're looking to improve your general fitness, tone your lower body, or build strength. Performing the squat requires using multiple muscle groups at the same time, making it an effective muscle-building compound movement to include into your workout routine. The main muscles groups used when doing a squat are the quadriceps, glutes and hamstrings.\r\n\r\nAlthough the squat is widely acknowledged as the ‘king of leg exercises’, other muscles groups are also involved, such as your core and even arms depending on the variation, so incorporating this exercise can help to tone your whole body.\r\n\r\nWhether you’re a complete beginner or a pro, this is a staple exercise to include into your gym routine. The squat can easily be adapted to suit your fitness level and abilities.\r\n\r\nFor beginners, the body weight squat, which is the most widely-known exercise would be a good one to start with. As you get more comfortable with the basic squat and your legs get stronger, you can make the squat more challenging by adding a variation that includes weights such as the barbell squat which used in Olympic weightlifting.",
                            Image = "squat-2x.jpg",
                            Name = "Squats",
                            reps = 10,
                            sets = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "The leg press is a compound exercise performed on a seated resistance machine. It has a similar movement pattern to the squat, but unlike the squat which uses stabilising muscles in the upper body and core, the leg press is a lower body movement only. The quads are the main muscle recruited in a leg press, but the hamstrings, glutes, and calves are all worked to a lesser degree. \r\n\r\nLeg presses can be used alongside squats, or as a replacement. While squats are better at working the full body, the leg press makes a great alternative for anyone who can't squat, for example due to balance or mobility issues, or an upper body injury. Unlike squats, the leg press doesn't require any technical skill which makes it ideal for beginners too.\r\n\r\nThere are a few types of leg presses, with the most common being the 45 degree leg press and the seated leg press. The 45 degree leg press is the more challenging of the two as the plate is pushed at a 45 degree incline, and can have a higher weight as plates can be loaded on. The seated leg press is more suited for beginners, however both are used in the same way and work the same muscles.",
                            Image = "leg-press.jpg",
                            Name = "leg press",
                            reps = 15,
                            sets = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Hamstring curls are isolation exercises which exclusively target the hamstrings. Isolation exercises often get a bad rep, but they can be really beneficial in addressing muscle imbalances. In this case, the hamstrings are typically weaker than the quadriceps, which means they don't always get pushed to full potential in compound movements as the quads take over. Combining compound movements with hamstring isolation exercises is the best way to increase the strength and size of your hamstrings. ",
                            Image = "leg-curl.png",
                            Name = "Hamstring curls",
                            reps = 15,
                            sets = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "When you're looking to target your legs and bum, you can't beat a lunge. They're safe and easy to perform, you can do them anytime, anywhere, and they work out pretty much all the muscles in your lower body. Key muscles targeted include gluts, quads, hamstrings, calves and core.\r\n\r\nKnown as a unilateral exercise, lunges work out one side of your body at a time. This helps improve your overall stability, giving your better coordination and balance to perform everyday activities.\r\n\r\nAnother positive of training one side of your body at a time is it allows you to ensure both sides of the body are getting an equal work out, rather than letting your stronger side do more of the work. \r\n\r\nLunges are particularly effective in giving your core muscles a work out as it takes some effort to remain upright as you perform the lunge. A stronger core will go some way to improving your posture and warding off lower back pain.\r\n\r\nAs the exercise targets large muscle groups, it can help give your metabolism a boost which will aid weight loss and tone up key target areas on your legs and bottom. \r\n\r\nBefore you plunge right in and give it a go, be sure to check out our top tips and our guide to performing some of our favourite lunges. ",
                            Image = "lunge-2x.jpg",
                            Name = "lunge",
                            reps = 12,
                            sets = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "The calves are made up of two muscles, the gastrocnemius muscle and the soleus muscle. These muscles play a part in many body functions, including walking, running, jumping, standing on your toes, and flexing your feet. The calf muscles also help to pump blood around the body! When your calf muscles contract, it pushes the blood through the legs to heart, against the force of gravity. \r\n\r\nStrengthening your calves helps to protect against injuries in the feet, ankles, and knees, and can improve your circulation. While the calves do get worked in many lower body compound exercises like squats and deadlifts, it's very hard to create enough of a training stimulus to encourage significant muscle growth without isolating the calves. Adding calf specific exercises like calf raises into your workouts can help to strengthen the muscles much faster, so you get the benefits of strong calves. Training your calves in isolation also prevents them from lagging behind other muscles, which can increase the risk of injuries during lower body exercises. ",
                            Image = "calf-raises.jpg",
                            Name = "calf raises",
                            reps = 30,
                            sets = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "The rear delts, or posterior deltoids, are the muscles which sit on the back of your shoulders. The rear delts help to stabilise the shoulders, and work alongside the muscles in your back to prevent your shoulders from hunching forward. They also play a key part in pulling movements. \r\n\r\nPeople with desk jobs or sedentary lifestyles tend to have poor posture, which leads to lead to muscles in the posterior chain like the rear delts becoming weaker than anterior muscles. This further worsens the posture and can cause long term issues, including back pain. \r\n\r\nTraining the rear delts, along with your back muscles, glutes, and hamstrings, helps to combat these muscle imbalances and correct your posture.",
                            Image = "rear-delt-fly.jpg",
                            Name = "posterior deltoids",
                            reps = 10,
                            sets = 3
                        });
                });

            modelBuilder.Entity("GymMvc.Models.Information", b =>
                {
                    b.HasOne("GymMvc.Models.User", "User")
                        .WithMany("information")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymMvc.Models.Login", b =>
                {
                    b.HasOne("GymMvc.Models.Information", "Information")
                        .WithOne("Login")
                        .HasForeignKey("GymMvc.Models.Login", "InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymMvc.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Information");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymMvc.Models.ScheduleWorkOut", b =>
                {
                    b.HasOne("GymMvc.Models.Schedule", "Schedule")
                        .WithMany("WorkOuts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymMvc.Models.WorkOut", "WorkOut")
                        .WithMany()
                        .HasForeignKey("WorkOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("WorkOut");
                });

            modelBuilder.Entity("GymMvc.Models.Information", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();
                });

            modelBuilder.Entity("GymMvc.Models.Schedule", b =>
                {
                    b.Navigation("WorkOuts");
                });

            modelBuilder.Entity("GymMvc.Models.User", b =>
                {
                    b.Navigation("information");
                });
#pragma warning restore 612, 618
        }
    }
}
